"""Render worked sizing examples to reports/EXAMPLES.md using the CLI."""
import contextlib
import io
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from servest.cli import main  # noqa: E402

CASES = [
    ("Sizing example: Mistral Small 4 on 4×H100, 100 users, 4k-token prompts, 30 s think time",
     ['estimate', '--model', 'mistralai/Mistral-Small-4-119B-2603', '--gpu', 'H100', '--gpus', '4', '--users', '100',
      '--isl', '4096', '--osl', '1024', '--think-time', '30']),
    ("Mistral Small 4, 8×H100, 128k-token document ingestion: how many users at ≥30 tok/s and TTFT ≤ 10 s?",
     ['capacity', '--model', 'mistralai/Mistral-Small-4-119B-2603', '--gpu', 'H100', '--gpus', '8', '--isl', '131072',
      '--osl', '1024', '--min-tps', '30', '--max-ttft', '10', '--think-time', '30']),
    ("Same on 8×B200",
     ['capacity', '--model', 'mistralai/Mistral-Small-4-119B-2603', '--gpu', 'B200', '--gpus', '8', '--isl', '131072',
      '--osl', '1024', '--min-tps', '30', '--max-ttft', '10', '--think-time', '30']),
    ("DeepSeek-V4.1-Flash on 8×H100, 100 users ingesting 128k-token documents (30 s think time)",
     ['estimate', '--model', 'deepseek-ai/DeepSeek-V4.1-Flash', '--gpu', 'H100', '--gpus', '8', '--users', '100',
      '--isl', '131072', '--osl', '1024', '--think-time', '30', '--tp', '8']),
    ("DeepSeek-V4.1-Flash on 8×B200, same load",
     ['estimate', '--model', 'deepseek-ai/DeepSeek-V4.1-Flash', '--gpu', 'B200', '--gpus', '8', '--users', '100',
      '--isl', '131072', '--osl', '1024', '--think-time', '30', '--tp', '8']),
    ("Load sweep: Llama-3.3-70B FP8 on 8×H200, 2k prompts",
     ['sweep', '--model', 'meta-llama/Llama-3.3-70B-Instruct', '--gpu', 'H200', '--gpus', '8', '--quant', 'fp8',
      '--isl', '2048', '--osl', '512', '--users', '1,16,64,256,1024']),
    ("Smallest H100 deployment for Qwen3-235B-A22B FP8 serving 200 users at ≥25 tok/s, TTFT ≤ 3 s",
     ['plan', '--model', 'Qwen/Qwen3-235B-A22B', '--gpu', 'H100', '--quant', 'fp8', '--users', '200',
      '--isl', '2048', '--osl', '512', '--min-tps', '25', '--max-ttft', '3']),
]

out = ['# Worked examples (generated by `scripts/examples.py`)\n',
       'Central estimates with 10th–90th percentile bands from held-out data. Long-context rows are physics '
       'extrapolations (few public measurements above 32k tokens) — validate on your own hardware.\n']
for title, argv in CASES:
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        main(argv + ['--offline'] if argv[0] != 'model' else argv)
    out.append(f'## {title}\n\n```\n$ servest {" ".join(argv)}\n\n{buf.getvalue().rstrip()}\n```\n')
path = os.path.join(os.path.dirname(__file__), '..', 'reports', 'EXAMPLES.md')
open(path, 'w').write('\n'.join(out))
print(open(path).read())
